const data = {
    product: [
      {
        _id: '3',
        name: 'Leather Jacket',
        slug: 'leather-jacket',
        image: '/images/pants1.jpg',
        price: 99.99,
        brand: 'Brand C',
        description: 'Genuine leather jacket for a stylish winter wardrobe.',
        category: 'Clothing',
        rating: 4.8,
        numReviews: 60,
        countInStock: 20,
        colors: ['Black', 'Brown'],
        sizes: ['M', 'L', 'XL'],
      },
      {
        _id: '4',
        name: 'Sneakers',
        slug: 'sneakers',
        image: '/images/pants2.jpg',
        price: 69.99,
        brand: 'Brand D',
        description: 'Comfortable and stylish sneakers for everyday wear.',
        category: 'Footwear',
        rating: 4.3,
        numReviews: 150,
        countInStock: 100,
        colors: ['White', 'Gray', 'Blue'],
        sizes: ['8', '9', '10', '11'],
      },
      {
        _id: '5',
        name: 'Smartwatch',
        slug: 'smartwatch',
        image: '/images/pants3.jpg',
        price: 199.99,
        brand: 'Brand E',
        description: 'Track your fitness and stay connected with this smartwatch.',
        category: 'Accessories',
        rating: 4.6,
        numReviews: 45,
        countInStock: 15,
        colors: ['Black', 'Silver'],
        sizes: ['One Size'],
      },
      {
        _id: '6',
        name: 'Casual T-shirt',
        slug: 'casual-t-shirt',
        image: '/images/shirt1.jpg',
        price: 19.99,
        brand: 'Brand F',
        description: 'Casual t-shirt perfect for lounging or going out.',
        category: 'Clothing',
        rating: 4.1,
        numReviews: 75,
        countInStock: 60,
        colors: ['Green', 'Yellow', 'White'],
        sizes: ['S', 'M', 'L'],
      },
      {
        _id: '7',
        name: 'Running Shoes',
        slug: 'running-shoes',
        image: '/images/shirt2.jpg',
        price: 79.99,
        brand: 'Brand G',
        description: 'Lightweight shoes designed for running and outdoor activities.',
        category: 'Footwear',
        rating: 4.7,
        numReviews: 110,
        countInStock: 90,
        colors: ['Red', 'Blue'],
        sizes: ['7', '8', '9', '10'],
      },
      {
        _id: '8',
        name: 'Backpack',
        slug: 'backpack',
        image:  '/images/shirt3.jpg',
        price: 39.99,
        brand: 'Brand H',
        description: 'Durable backpack for daily use and travel.',
        category: 'Accessories',
        rating: 4.4,
        numReviews: 95,
        countInStock: 25,
        colors: ['Black', 'Gray'],
        sizes: ['One Size'],
      },
       
    ],
}

export default data